### ISSUE TITLE
Saving Trained Model

### ISSUE THREAD

**Issue by michael-camilleri** [gorjanradevski/revisiting-spatial-temporal-layouts#4]
Hi Gorjan

Once trained, how can I save a CACNF model? does setting the save_model_path store also the backbones (including the fine-tuned Resnet) or do I need to store these (and load them) separately using the resnet_model_path and save_backbone_path?

**Comment by gorjanradevski** [comment]
Hi Michael, using the `save_model_path` saves the whole model, including the classifier, useful if you want to use the same model for inference. The `save_backbone_path`, saves the whole model, excluding the classifier. Useful if you want to fine-tune the backbone on a different dataset, with different number of classes.

When performing inference, you should create the model `model = CrossAttentionCentralNetFusion`, and then load the full model that you saved with `save_model_path` (see `inference.py`). On the other hand, if you just want to load the backbone, and have a randomly initialized classifier with different number of classes, you can provide the `load_backbone_path` and set `freeze_backbone` to `True` or `False`, in case you want to fine-tune the backbone or not, respectively. 

The fact that you need to **always** provide the `resnet_model_path` when creating a model is poor API design, but didn't have time to think about a workaround. Ideally, if you want to load either a backbone, or a full model, you should not be obliged to provide the `resnet_model_path`.

**Comment by michael-camilleri** [comment]
As long as the resnet is still loaded correctly, I don't mind passing a path.

**Comment by gorjanradevski** [comment]
I'm closing this issue, feel free to reopen if the problem persists.
